version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    environment:
      - MAIN_BUCKET=""
      - GOOGLE_APPLICATION_CREDENTIALS=""
      - ENV=PROD
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@admin.com
    build: .
    command: bash -c "dos2unix /src/tools/run.sh && /src/tools/run.sh"
    ports:
      - "8000:8000"
    depends_on:
      - db